version: &imageVersion "14028125319"
global:
  version: *imageVersion
okto-sdkv2-nextjs-template-app:
  environment: production
  project: okto
  namespaceOverride: oktohq
  image:
    registry: ghcr.io
    repository: okto-hq/okto-sdkv2-nextjs-template-app
    pullPolicy: IfNotPresent
    tag: *imageVersion
  imagePullSecrets:
    - name: oktohq-registry
  deployment:
    resources:
      limits:
        cpu: 700m
        memory: 700Mi
      requests:
        cpu: 500m
        memory: 500Mi
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 2
    DDService: okto-sdkv2-nextjs
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: node
        whenUnsatisfiable: ScheduleAnyway
  service:
    # serviceName: 
    ports:
      - port: 3000
        portName: http
        protocol: TCP
    type: ClusterIP
  ingress:
    enabled: true
    domain: okto.tech
    exposePort: http
    scheme: http
    hosts:
      - host: nextjs-template-v2.okto.tech
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  envFromSecrets:
    - variable: NEXT_PUBLIC_CLIENT_SWA
      secretId: &oktohq-sdkv2-nextjs oktohq/okto-sdkv2-nextjs
      secretKey: NEXT_PUBLIC_CLIENT_SWA
    - variable: NEXT_PUBLIC_CLIENT_PRIVATE_KEY
      secretId: *oktohq-sdkv2-nextjs
      secretKey: NEXT_PUBLIC_CLIENT_PRIVATE_KEY
  tolerations:
    - effect: NoSchedule
      key: application
      operator: Equal
      value: okto
    - effect: NoSchedule
      key: arch
      operator: Equal
      value: arm64
  nodeSelector:
    application: okto
    arch: arm64
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    runAsGroup: 7777
    runAsUser: 7777
  deploymentStrategy:
    rollingUpdate:
      maxUnavailable: 50%
